seed: 2345
dataset: 'imdb'
fully: False

n_layers: 6
dim_embed: 300
dim_model: 300
dim_ff: 600
num_heads: 10
dropouti: 0.5
dropouth: 0.1
dropouta: 0.3
dropoutc: 0.5
rel_pos: True
ffn: True 

n_epochs: 100
lr: 1.e-4
batch_size: 32
dev_batch_size: 32
opt_wrapper: 'exp_decay'
log_interval: 40
